### PR TITLE
WordPress article

### PR DESCRIPTION
**Pull request by weppos**

### CODE REVIEW

**Comment by jcaudle** [comment]
This looks very good @weppos. Is there a reason you didn't mention the Wordpress one-click service? I think it defaults to using `blog.#{domain_name}`, but that could be edited if the entire site will be hosted with Wordpress.com

**Comment by weppos** [comment]
> Is there a reason you didn't mention the Wordpress one-click service?

I didn't recall one. Feel free to add another "steps" section where you cover the 1-click service.

**Comment by weppos** [comment]
@jcaudle let me know if you are going to add the section for WordPress.

**Comment by jcaudle** [comment]
I think this is fine to ship as it is. Since the flow is going to be quite different and the use case is pretty narrow (the service just adds a record to the `blog` subdomain), I don't know if emphasizing the service is worth it here.

**Pull request merged**
