### PR TITLE
Update account-users.markdown

### PR DESCRIPTION
**Pull request by SarahCaminiti1**
Made some edits

- member and user was used interchangeably and it was confusing. Since we call the user a "member" on the app, I changed all of the users to member, accept for one where I said user, or member, to define what we mean.

### CODE REVIEW

**Comment by itsalyse** [comment]
We call them "users" in a lot more places in support:
 https://support.dnsimple.com/search/?q=user 
and across the app: 
https://github.com/dnsimple/dnsimple-app/search?q=user&type=Code

I'm not sure this is a quick fix, or that we should implement it without more opinions.

**Comment by SarahCaminiti1** [comment]
@itsalyse I prefer "user" to "member" but it's called "member" in the app...so it's a little confusing

**Comment by itsalyse** [comment]
After doing a little more thinking/research, I don't think this is something we want to (or need to) change. There are places where it's more appropriate to use "user" or "member", and places where it sounds flat out weird to say "member". After doing some research, it looks like it's not against best practices to use these terms interchangeably – Google, Microsoft, Stripe, and Zoom all do it, too.

**Comment by itsalyse** [comment]
I edited it so it changes all instances of "user" to "member" when talking about people associated with a multi-user account, but leaves them as "user" if they're not part of it yet/were removed. @kayla-broussard do you have thoughts and/or opinions on this? 

I also think that if we do want to streamline it, we should change instances of "member" to "user" in the app. It makes more sense, and it's significantly easier to do that than to change all instances of "user" to "member".

**Comment by kayla-broussard** [comment]
> I edited it so it changes all instances of "user" to "member" when talking about people associated with a multi-user account, but leaves them as "user" if they're not part of it yet/were removed. @kayla-broussard do you have thoughts and/or opinions on this?
> 
> I also think that if we do want to streamline it, we should change instances of "member" to "user" in the app. It makes more sense, and it's significantly easier to do that than to change all instances of "user" to "member".

I'd agree with all of this 👍 I wouldn't wholesale change all instances within the support repo, and I think this strikes a balance. To address your second point, there would also be times that "member" within the app wouldn't make as much sense as "user".

**Comment by SarahCaminiti1** [comment]
I think this is great! Thank you both!

**Pull request merged**
