### PR TITLE
Article on how to add an HNS domain to DNSimple

### PR DESCRIPTION
**Pull request by DXTimer**
This PR adds an article on how a user can add an HNS domain to DNSimple, and what are the limitations they can expect in doing so.

Belongs to https://github.com/dnsimple/dnsimple-business/issues/1484

Preview:
https://deploy-preview-891--dnsimple-support.netlify.app/articles/dnsimple-and-handshake/

### CODE REVIEW

**Comment by weppos** [comment]
Good work. What do you think about updating the article to be a generic "DNSimple and Handshake", and place "Add a domain" as a section?

This would allow, for instance, to also add a brief preamble about Handshake, and expand the article in the future. I think it would be helpful to also add a short section about recommended resolvers.

**Comment by weppos** [comment]
I'll engage customer success as well /cc @SarahCaminiti1 and, once ready, @itsalyse for the final review.

**Comment by DXTimer** [comment]
> Good work. What do you think about updating the article to be a generic "DNSimple and Handshake", and place "Add a domain" as a section?
> 
> This would allow, for instance, to also add a brief preamble about Handshake, and expand the article in the future. I think it would be helpful to also add a short section about recommended resolvers.

I considered adding a section to explain what Handshake was, but decided against doing it since the blog post will cover that and more, and can be linked to the page for anyone that stumbles on the page and wants to learn more. If you still think it's better to have the preamble in the support article as well, then let me know and I can update it.

**Comment by weppos** [comment]
> If you still think it's better to have the preamble in the support article as well, then let me know and I can update it.

I think I would. The content on the blog post tends to expire more quickly, compared to a knowledge base. By its own nature, the blog has a more "point in time" view and the relevance of the content fades over time.

Having a short intro in the support page, IMHO, would have a stronger long-term emphasis.

**Review by weppos — APPROVED** [review]
Good for me. I'd engage customer success and then Alyse.

**Review by SarahCaminiti1 — APPROVED** [review]
This looks great!

**Review by itsalyse — APPROVED** [review]

**Pull request merged**
