### PR TITLE
Let's Encrypt Wildcard Certificates

### PR DESCRIPTION
**Pull request by OleMchls**
Once this feature goes into public beta this PR documents the usage.

### CODE REVIEW

**Comment by weppos** [comment]
@itsalyse I see you committed changes to this branch that are only referring to the CAA wildcard page.
https://github.com/dnsimple/dnsimple-support/pull/388/commits/382caa495c9e8e98bbfe5350a6fd640400633ca6

Was it intentional? It seems these changes are related to a different PR to me.

@OleMchls can you please work with @itsalyse to get those changes moved to a different PR and/or shipped?

**Comment by OleMchls** [comment]
@weppos please re-review I moved @itsalyse changes into a own PR (#391) please re-review

**Comment by weppos** [comment]
I re-added @itsalyse for review since we moved the unrelated changes to https://github.com/dnsimple/dnsimple-support/pull/388

**Comment by itsalyse** [comment]
@weppos that was definitely not intentional. They were two separate files, not sure why it did that. Git was merging a lot of my PRs on Tuesday, I had to go through and separate 2 or 3 I've been working on.

**Pull request merged**
