### PR TITLE
Updates transfer out doc

### PR DESCRIPTION
**Pull request by arnamak**
Quick update to the screenshots in the "Requesting a Transfer code" document.

### CODE REVIEW

**Comment by weppos** [comment]
@arnamak the domains-domain-link.png references the account domain listing. I suggest to use a screenshot from that section instead of a dashboard search, to be coherent with the instructions where the screenshot is in use.

**Comment by arnamak** [comment]
@weppos Okay. There is no longer a search for the account domain listing though, and the search from the navbar displays the results as seen here.

**Comment by weppos** [comment]
@arnamak that's a good point. we need then to be consistent so either update che screenshot and the text of the articles where it's used, or update the screenshot preserving the same area. I'll leave up to you the decision of the path.

**Comment by arnamak** [comment]
@weppos I elected to update the wording, and use the screenshot from the search.

**Comment by weppos** [comment]
👍  looks good to me. Please if the screenshot is used elsewhere, make sure to update all the corresponding articles.

**Pull request merged**
