### PR TITLE
Adds description for onboarding DNS records to a zone

### PR DESCRIPTION
**Pull request by sbastn**
This PR adds a section on the DNS hosting page describing the new onboarding DNS page.

See https://deploy-preview-1180--dnsimple-support.netlify.app/articles/dns-hosting/#onboarding-dns-records-to-your-domain for preview

### CODE REVIEW

**Comment by sbastn** [comment]
@itsalyse can I please have your review on this PR? Thank you!

**Comment by stephanoodle** [comment]
> @Pemacaa or @stephanoodle could one of you take a look at this too? This article will have further updates later, but want to make sure anything we're adding in the meantime is reviewed.

I took a look. Here's what I found:

> Onboarding DNS records

Why was onboarding chosen vs adding? We typically tell customers to add records. 

> Configuring [two-way connectors](https://support.dnsimple.com/categories/connectors/). With two-way connections, both sides of the service are configured and monitored automatically.

We do not mention anywhere that I am aware of in the support documentation that Heroku and Netlify are two-way connectors. This is a new term and if we are using it, it should probably be mentioned in those two docs at least. 

> Manually entering DNS records in the DNS [record editor](https://support.dnsimple.com/articles/record-editor/).

Right below this, we mention the DNS record editor, however, the link is for the entirety of [DNS record editor]. 

Other than that, this looks good to me.

**Comment by Pemacaa** [comment]
I have the same question as @stephanoodle about why we are using "Onboarding DNS records" instead of adding. The rest looks good to me.

**Review by itsalyse — APPROVED** [review]

**Comment by sbastn** [comment]
Thanks @Pemacaa and @stephanoodle for your feedback. I've incorporated it to the changes.

I used 'two-way connectors' since it's how we call them here: https://dnsimple.com/benefits/integrations but you're right that we don't use the same concept in the support docs, so I replaced it.

**Pull request merged**
