### PR TITLE
Reflect new plan names in plan-changes page

### PR DESCRIPTION
**Pull request by nestorsalceda**
This PR:

- Updates the screenshots to match last pricing release
- Makes the label to match the screenshots

Belongs to https://github.com/dnsimple/dnsimple-business/issues/1741

### CODE REVIEW

**Review by ggalmazor — APPROVED** [review]

**Review by jacegu — APPROVED** [review]

**Comment by itsalyse** [comment]
A couple questions here — 

It says seats and team members aren't allowed, but then talks about a seat allowance — these are conflicting, do they have 3 seats or 0 seats? 

Do they have to remove everyone and then re-add them or just remove X number to align with the new seat allowance?

**Comment by nestorsalceda** [comment]
These are good questions, let me to answer inline:

> A couple questions here — 
> 
> It says seats and team members aren't allowed, but then talks about a seat allowance — these are conflicting, do they have 3 seats or 0 seats?

They are two features, but they are quite related:

- The Solo plan does not allow extra users, is only applicable to an individual
- The Teams plan includes 3 seats, but you can purchase additional seats 

Then in this case, there are 4 seats (3 included + 1 purchased) and it requires to remove the purchased one. In case there are more than one user, other message telling about the amount of users is shown.

> Do they have to remove everyone and then re-add them or just remove X number to align with the new seat allowance?

To make it compatible, it needs to remove one user to align with the seat allowance. From my POV this is the call to action, to remove the purchased extra seat.

Maybe @sbastn can extend the explanation.

Thank you @itsalyse !

**Comment by aeden** [comment]
If not for this PR, in the future I'd like to see a new PR where the example uses a generic account, not one from a team member, for all of the screenshots.

**Comment by nestorsalceda** [comment]
> If not for this PR, in the future I'd like to see a new PR where the example uses a generic account, not one from a team member, for all of the screenshots.

@aeden thank you for the feedback.

I changed the screenshots to use something more generic like John Doe.

**Review by aeden — APPROVED** [review]

**Comment by itsalyse** [comment]
@nestorsalceda would it work to clarify it like this: 

Solo plan users: 

> You have 4 seats in use, but your new plan has an allowance of 0 seats. To align with the new plan’s seat allowance, please remove 4 user(s) to reduce the number of seats used. 

or 

Team plan users: 

> You have 4 seats in use, but your new plan has an allowance of 3 seats. To align with the new plan’s seat allowance, please remove 1 user(s) to reduce the number of seats used.

**Comment by nestorsalceda** [comment]
Thank you so much @itsalyse !

I updated the screenshot and added a change in the application to update this copy. I changed the word to member instead of user because is the word we use in this context.

When I get your approval, I will merge and ship! 🙇🏻

**Comment by itsalyse** [comment]
@nestorsalceda there's a small typo - it should be `member(s) `

Otherwise looks good to me!

**Comment by itsalyse** [comment]
Hey @nestorsalceda I know this has been merged, but in



"To align with the new plan's seat allowance, please reduce until 3 the amount of
seats:" doesn't make sense. You'd have to say "please reduce the amount of seats to 3"

**Comment by nestorsalceda** [comment]
Let me open a new one fixing this @itsalyse

**Pull request merged**
