### PR TITLE
Domain list UI updates

### PR DESCRIPTION
**Pull request by lokst**
Update the following support pages to reflect the latest UI improvements to domain lists:
- "Organizing and Labeling Domains"
- "Record Editor"
- "Transferring a Domain to Another DNSimple Account"

### CODE REVIEW

**Review by dallasread — APPROVED** [review]
This looks great! Thanks for doing this!

**Review by sbastn — APPROVED** [review]
Looks good! A minor comment on the size of the new images, in some cases, they have increased by 1000% in size. Please run them through tinypng.com or another image optimizer before committing.

We use to automatically do this, but we had to remove it because of some issues.

**Comment by lokst** [comment]
> Looks good! A minor comment on the size of the new images, in some cases, they have increased by 1000% in size. Please run them through tinypng.com or another image optimizer before committing.
> 
> We use to automatically do this, but we had to remove it because of some issues.

Thanks for the tip! I will get that done 👍

**Comment by lokst** [comment]
@sbastn I ran the images through tinypng.com, and got about 20-30% reduction in the file sizes. Do you think these reductions are enough: https://github.com/dnsimple/dnsimple-support/pull/950/commits/1151368ebd3b35162e340644e033300c4dd5c78f ? 🙂

**Comment by sbastn** [comment]
@lokst Good enough for now. Ship and we'll adjust if necessary.

**Comment by lokst** [comment]
@sbastn Got it, thanks for taking a look! 🙂

**Pull request merged**
