### PR TITLE
Update SSL installation articles

### LINKED ISSUE #74: "Using an SSL Certificate with Windows" article is out of date
The [Using and SSL Certificate with Windows](http://support.dnsimple.com/articles/ssl-certificate-with-windows/) page is out of date and even includes a dead link. I think it may be possible to replace this page with a new panel in the certificate installer wizard, but will need to do some research.

### PR DESCRIPTION
**Pull request by jcaudle**
This article brings the document on using an SSL certificate with Microsoft IIS up to date. It also closes #74.

### CODE REVIEW

**Comment by weppos** [comment]
@jcaudle well done! 👏 

For the old windows article, instead of removing/redirecting it, I suggest to replace it with the draft I prepared at https://github.com/dnsimple/dnsimple-support/compare/article-stubs?expand=1#diff-f8a6a651db92cbb91691f39586bc821c

We don't have the articles about Nginx and Apache yet, you can comment them out temporarily or expand the stub as you did for IIS.

**Comment by jcaudle** [comment]
@weppos I'd removed it since that same branch had a redirect in place. I'll remove the redirect and update the article.

**Comment by jcaudle** [comment]
Apparently I misread that redirect, so I'll leave the redirect around. @weppos do you know what https://github.com/dnsimple/dnsimple-support/compare/article-stubs?expand=1#diff-16e2386ec454cf94fed2be96973ba154R62 is meant to address?

**Comment by weppos** [comment]
@jcaudle I actually don't know, it's possible we had that page at that time. I'd leave the redirect out (also notice that it seems this PR removed an existing redirect for the hostname.

I'd leave both the windows page you removed (and add the content as from the branch), and the new one you wrote.

**Comment by weppos** [comment]
@jcaudle I've removed the "ready-for-review" label as I did not know if it was a work in progress or not. Feel free to re-add it once ready for review. In the meanwhile, I made a few tweaks.

It looks very good to me.

**Comment by jcaudle** [comment]
It's ready for review. I've added the label back and have resolved the merge conflict with master.

**Comment by weppos** [comment]
@jcaudle do you mind to update https://support.dnsimple.com/articles/what-is-ssl-certificate-chain/, specifically the FAQ

> How do I install the Intermediate SSL certificates?

I suggest to rephrase it based on the new wizard, and point to the installation article.

**Comment by jcaudle** [comment]
@weppos I've updated the FAQ. If you like what you see, feel free to merge it. Otherwise I'll address any other changes in the morning. 😃

**Pull request merged**
