### PR TITLE
Adding dual CTA to the support site

### PR DESCRIPTION
**Pull request by dperrymorrow**
add dual cta to the header of the support site

belongs to: https://github.com/dnsimple/dnsimple-business/issues/2029

copy added to support this work here https://docs.google.com/document/d/1iGhuAnDlQRDys37fpsdBs1NftRHHlpHoKMD61iaKngo/edit

### CODE REVIEW

**Comment by dperrymorrow** [comment]
Screenshot 2024-09-27 at 1 26 49 PM
Screenshot 2024-09-27 at 1 26 40 PM

**Comment by dperrymorrow** [comment]
Screenshot 2024-09-27 at 1 53 08 PM
Screenshot 2024-09-27 at 1 53 01 PM

**Review by laetitiaeden — APPROVED** [review]
Thank you

**Review by sbastn — COMMENTED** [review]
There is a conflict with the section below which also says 'Get Started' and 'Getting Started'. @laetitiaeden @itsalyse, can we consider rewriting this section?

Screenshot 2024-09-30 at 09 18 39

**Comment by laetitiaeden** [comment]
The CTA of this page goes to the support documentation but you are correct it is problematic. @sbastn do you know how many people click on the Get Started going to the support doc? That will help us make a decision thank you.

**Comment by sbastn** [comment]
@laetitiaeden We had 69 clicks in the last 90 days. See https://us.posthog.com/project/18533/insights/kZKOy8bj for more details.

**Comment by itsalyse** [comment]
The button should say View Articles 

"Read Article" sounds like it's taking me to a specific single article

**Comment by dperrymorrow** [comment]
Updated:
Screenshot 2024-10-02 at 2 03 34 PM

**Pull request merged**
