### PR TITLE
Add stateful trades contact change docs

### PR DESCRIPTION
**Pull request by juankuquintana**
This PR:
- Refreshes outdated contact screens
- Brings up to date docs for contact update
- Adds a section for cancelling / pending contact change

### CODE REVIEW

**Comment by juankuquintana** [comment]
@itsalyse your help is appreciated with this one, I'm particularly unsure about the new section title "monitoring"

**Review by kntsoriano — APPROVED** [review]
Nice :+1:

**Comment by itsalyse** [comment]
There's a typo on this screen 


It should say 'could not be updated'

**Review by itsalyse — APPROVED** [review]
Noted an edit needed to one of the screens but the support docs lgtm 👍

**Comment by juankuquintana** [comment]
Thank you Alyse!

**Pull request merged**
