### PR TITLE
Update recovery code documentation

### PR DESCRIPTION
**Pull request by lokst**
Document how to use a recovery code to disable MFA when you are unable to remove an MFA method, and how to re-generate recovery codes.

### CODE REVIEW

**Review by dallasread — APPROVED** [review]
LGTM, thanks!

**Review by sbastn — APPROVED** [review]
LGTM @lokst. ~~Make sure to remove your personal email from the screenshots.~~ Nevermind, you were using example.com!

**Review by itsalyse — CHANGES_REQUESTED** [review]
image

There's a typo here, it should say 

> You're a member

**Comment by lokst** [comment]
@itsalyse Thanks for the review! I'll fix the typo in the app and then update the screenshot 👍

**Pull request merged**
