### PR TITLE
Document scoped access tokens

### PR DESCRIPTION
**Pull request by lokst**
Document scoped access tokens

### CODE REVIEW

**Review by dallasread — APPROVED** [review]
This looks great!

What do you think about including something about seeing the last updated timestamp on the index page?

**Comment by lokst** [comment]
> What do you think about including something about seeing the last updated timestamp on the index page?
@dallasread Great idea! Added 👍

**Review by kojdm — APPROVED** [review]
LGTM! 💯

**Comment by itsalyse** [comment]
One small change to this screen: 


There's a comma splice in the instructions. It should either be 

> Keep a copy of this token — we won't show it again. 

or 

> Keep a copy of this token. We won't show it again. 


Everything else looks good!

**Comment by lokst** [comment]
Thanks for catching that @itsalyse ! Just updated the screenshot 🙂

**Review by itsalyse — APPROVED** [review]

**Pull request merged**
