### PR TITLE
Support pages for the DNSimple dashboard and domain list

### PR DESCRIPTION
**Pull request by aeden**
Two new support pages for the dashboard and domain list.

### CODE REVIEW

**Comment by SarahCaminiti1** [comment]
Google Doc domain list: https://docs.google.com/document/d/1yJF-gUCD2D533djYgM5qj_jk5_oWti0c1Q8AB6U7sYA/edit?usp=sharing

**Comment by SarahCaminiti1** [comment]
Screenshots are here: https://drive.google.com/drive/folders/11VDo-h97s5xjU-HqNxPnx6j11bfxpcHK - I'll be unable to approve this if it's finished this week, but I approve what's in Google Docs and am sure it will all be good to go.

**Comment by aeden** [comment]
@itsalyse @stephanoodle please review. Thank you.

**Review by itsalyse — APPROVED** [review]
I made some updates for formatting so the sections look cleaner (headers v bullets), and edited for style consistency

**Review by stephanoodle — APPROVED** [review]

**Pull request merged**
